name: Talend Demo Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Talend CommandLine
      run: |
        wget https://path-to-talend-commandline.zip
        unzip talend-commandline.zip -d talend-cli

    - name: Build Talend Project
      run: |
        ./talend-cli/Talend-Studio-linux-x86_64 -nosplash \
          -application org.talend.commandline.CommandLine \
          -consoleLog \
          -clean -data workspace \
          -log log.txt \
          buildProject -p <ProjectName> -u <GitRepoURL>
