name: Talend Demo Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Java environment
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' # Required: OpenJDK distribution to use

    # Step 3: Build with Maven
    - name: Build project
      run: mvn clean package

    # Step 4: Upload build artifact (e.g., .jar file)
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: talend-demo-artifact
        path: target/*.jar   
