name: Validate Talend Repository

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Verify Repository Structure
    - name: Check Required Files
      run: |
        echo "Checking for required Talend files..."
        test -f talend.project || (echo "Missing talend.project file!" && exit 1)
        test -d process || (echo "Missing process directory!" && exit 1)
        echo "All required files and directories are present."

    # Step 3: (Optional) List All Jobs and Components
    - name: List Jobs and Components
      run: |
        echo "Listing jobs in process directory:"
        ls -R process/
        echo "Listing components in components directory:"
        ls -R components/

    # Step 4: (Optional) Zip Repository for Deployment
    - name: Archive Repository
      run: |
        zip -r TalendGitDemo.zip ./*
    - name: Upload Archive
      uses: actions/upload-artifact@v3
      with:
        name: talend-repository
        path: TalendGitDemo.zip
