name: Merge Develop to Main

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  merge:
    name: Merge Develop to Main
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch All Branches
        run: git fetch --all

      - name: Checkout Main Branch
        run: git checkout main

      - name: Merge Develop
        run: |
          git merge develop --no-edit
          git push origin main
