name: Merge Develop to Main

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types:
      - closed

permissions:
  contents: write

jobs:
  merge:
    name: Merge Develop to Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch All Branches
        run: |
          git fetch --all
          git checkout develop
          git pull origin develop

      - name: Checkout Main Branch
        run: git checkout main

      - name: Merge Develop
        run: |
          git merge origin/develop --no-edit --allow-unrelated-histories
          git push origin main
